### ISSUE TITLE
  It seems that I have some files in the “missing archives” list，how can i get in touch with project staff？

### ISSUE THREAD

**Issue by cdzxc** [pandabuilder/pandachaika#11]
It seems that I have some files in the “missing archives” list，how can i get in touch with project staff？

**Comment by pandabuilder** [comment]
You can send an email directly, it's on the about section.

Or use the submit form on the site with the information, but I wouldn't be able to answer back.

**Comment by cdzxc** [comment]
If I provide these documents, I hope to get an account of this site(pandachaika), although I don't know what rights a registered account can get. If this is a trust issue, you can confirm  my nickname on EH ,which is consistent  on GitHub

**Comment by pandabuilder** [comment]
It is possible, although there's no benefits to it. It's mostly to manage, check, and review what's added or submitted.
If you want to contribute files that are missing, the most clean way to do it is through the submit form or a direct email.
