### ISSUE TITLE
fakku failed fetching

### ISSUE THREAD

**Issue by kiyoko123** [pandabuilder/pandachaika#7]
2021-03-18 22:12:29 ERROR [core.providers.fakku.parsers] Failed fetching: https://www.fakku.net/hentai/creamy-english, gallery might not exist
2021-03-18 22:12:29 INFO [core.web.crawler] Web Crawler links crawling done.

not sure what caused this. but I used the default apikey (panda_backup) on settings.ini
maybe it was the problem? if so is there any way to get my own "apikey"?

**Comment by pandabuilder** [comment]
api_key parameter is an internal key which is used access the server itself through the web for management.
It does not make a difference regarding the fetching of links.

The parser which seems to give you an error, might be because of outdated code, which I haven't updated in a while.

I also must note that the fakku parser itself is only for metadata, it does not download archives, in case you were using it for that!

**Comment by kiyoko123** [comment]
oh it was nothing related to api_key

> I also must note that the fakku parser itself is only for metadata, it does not download archives, in case you were using it for that!

yeah I know this I wanna do this for metadata archiving

**Comment by kiyoko123** [comment]
> The parser which seems to give you an error, might be because of outdated code, which I haven't updated in a while.

I hope you don't mind to update it

**Comment by pandabuilder** [comment]
I tested the link you posted with the live site, and it parsed it correctly.

Same code is the one I just pushed here (a01d49b673164bc8ed158c4613509da6bf4924a4), you could try with that.

**Comment by kiyoko123** [comment]
still gave error to me
2021-03-19 01:42:59 ERROR [core.providers.fakku.parsers] Failed fetching: https://www.fakku.net/hentai/spread-the-peace-english, gallery might not exist

**Comment by kiyoko123** [comment]
tried the same link (https://www.fakku.net/hentai/creamy-english) and still same
i've cloned the latest repo

**Comment by pandabuilder** [comment]
Strange, can you open the link directly on a browser from the same machine? That error doesn't make differentiate a network error from a parsing error, so it could be any of those.

**Comment by kiyoko123** [comment]
nevermind
I reboot the machine then did **pip install -r requirements.txt** and it perfectly working somehow

**Comment by kiyoko123** [comment]
thanks

**Comment by pandabuilder** [comment]
Good to hear!
